### ISSUE TITLE
Are relationships async?

### ISSUE THREAD

**Issue by kylealwyn** [coverhound/active-redux#18]
If `Article.find` does cache and api lookup and returns a promise, does that in turn mean that relationship lookups have the same functionality?

take for example:
```js
const article = await Article.findById(3);
const comments = await article.comments;
```

**Comment by berfarah** [comment]
They have to be, yeah. Not sure if they should continue to be properties.

**Comment by berfarah** [comment]
See https://github.com/coverhound/active-redux/pull/20
